### PR TITLE
Fixes `NullPointerException` crash.

### PR DESCRIPTION
**Pull request by Hephaestus-Dev**
Issues #49 and #55.

### CODE REVIEW

**Comment by Dragonoidzero** [comment]
Blessed

**Comment by diabolical17** [comment]
This fixes the elytra crash bug, rejoice and get this merged and published @bernie-g

**Comment by bernie-g** [comment]
Will get this merged in soon, got a bunch of other PRs I need to look at as well.

**Comment by Snivyer1910** [comment]
I think you typoed something

**Comment by diabolical17** [comment]
Could you merge this soon? We can't develop or release any version of our mod as this bug breaks everything

**Pull request merged**
