### PR TITLE
Add item animation controller ID tracking

### PR DESCRIPTION
**Pull request by DenimRed**
This fixes the issue with items using a non-deterministic ID when trying to animate, allowing all connected clients to see the same ID.
It does this by storing an integer ID with the items' NBT data.
To ensure that there are no conflicts, the last available ID is stored with the world's NBT data, similar to how vanilla maps work.
(In particular, the new `GeckoLibIdTracker` can be extended to store many different IDs, but for now it's only used for items.)

### CODE REVIEW

**Review by AzureDoom — APPROVED** [review]

**Comment by Icosider** [comment]
@DenimRed, do not use a global item object. U need send packet with animation id and target id, and then in client handler getEntityById(or similar), get current ItemStack and doAnimation for item. It would also be worth creating an ItemAnimation interface, so it will be more convenient.

**Comment by AzureDoom** [comment]
> @DenimRed, do not use a global item object. U need send packet with animation id and target id, and then in client handler getEntityById(or similar), get current ItemStack and doAnimation for item. It would also be worth creating an ItemAnimation interface, so it will be more convenient.

An interface, `ISyncable`, which will handle most of the stuff has already been discussed on the discord, a planned second pr is planned for it since this one isn't complete and more issues have been discovered (non-stackable items)

**Comment by Icosider** [comment]
"discovered (non-stackable items)" for weapons, this is normal

**Comment by AzureDoom** [comment]
For non-weapons its not, it's a breaking feature non the less that is aware of and is being worked on

**Pull request merged**
